// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentCardCenterService.Data;

#nullable disable

namespace PaymentCardCenterService.Migrations
{
    [DbContext(typeof(PCCDbContext))]
    [Migration("20250915132035_InitialPCCDatabase")]
    partial class InitialPCCDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentCardCenterService.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiUrl = "http://localhost:7000",
                            ContactEmail = "contact@bank1.com",
                            ContactPhone = "+381-11-1234567",
                            CreatedAt = new DateTime(2025, 9, 15, 13, 20, 34, 370, DateTimeKind.Utc).AddTicks(6562),
                            IsActive = true,
                            Name = "Bank1 (Primary Bank)"
                        },
                        new
                        {
                            Id = 2,
                            ApiUrl = "http://localhost:7100",
                            ContactEmail = "info@bank2.com",
                            ContactPhone = "+381-11-7654321",
                            CreatedAt = new DateTime(2025, 9, 15, 13, 20, 34, 370, DateTimeKind.Utc).AddTicks(6829),
                            IsActive = true,
                            Name = "Bank2 (External Bank)"
                        });
                });

            modelBuilder.Entity("PaymentCardCenterService.Models.BinRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CardType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("BinCode")
                        .IsUnique();

                    b.ToTable("BinRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 1,
                            BinCode = "4111",
                            CardType = "Visa",
                            CreatedAt = new DateTime(2025, 9, 15, 13, 20, 34, 371, DateTimeKind.Utc).AddTicks(4560),
                            Description = "Bank1 Visa kartice",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            BankId = 1,
                            BinCode = "5555",
                            CardType = "MasterCard",
                            CreatedAt = new DateTime(2025, 9, 15, 13, 20, 34, 371, DateTimeKind.Utc).AddTicks(4949),
                            Description = "Bank1 MasterCard kartice",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            BankId = 2,
                            BinCode = "4222",
                            CardType = "Visa",
                            CreatedAt = new DateTime(2025, 9, 15, 13, 20, 34, 371, DateTimeKind.Utc).AddTicks(4951),
                            Description = "Bank2 Visa kartice",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            BankId = 2,
                            BinCode = "5444",
                            CardType = "MasterCard",
                            CreatedAt = new DateTime(2025, 9, 15, 13, 20, 34, 371, DateTimeKind.Utc).AddTicks(4952),
                            Description = "Bank2 MasterCard kartice",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("PaymentCardCenterService.Models.BinRange", b =>
                {
                    b.HasOne("PaymentCardCenterService.Models.Bank", "Bank")
                        .WithMany("BinRanges")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("PaymentCardCenterService.Models.Bank", b =>
                {
                    b.Navigation("BinRanges");
                });
#pragma warning restore 612, 618
        }
    }
}
