// <auto-generated />
using System;
using BitcoinPaymentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitcoinPaymentService.Migrations
{
    [DbContext(typeof(BitcoinPaymentDbContext))]
    [Migration("20250920133846_InitialSqlServerMigration")]
    partial class InitialSqlServerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitcoinPaymentService.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("amount");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("buyer_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency1");

                    b.Property<string>("Currency2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TelecomServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("telecom_service_id");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BuyerEmail")
                        .HasDatabaseName("IX_transactions_buyer_email");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_transactions_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_transactions_status");

                    b.HasIndex("TelecomServiceId")
                        .HasDatabaseName("IX_transactions_telecom_service_id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_transactions_transaction_id");

                    b.ToTable("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
